apiVersion: v1
kind: Service
metadata:
  name: java-grpc-server
spec:
  ports:
    # Port that accepts gRPC and JSON/HTTP2 requests over HTTP.
    - port: 80
      targetPort: 9000
      protocol: TCP
      name: http2
  selector:
    app: java-grpc-server
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: java-grpc-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: java-grpc-server
    spec:
      containers:
        - name: esp
          image: gcr.io/endpoints-release/endpoints-runtime:1
          args: [
            "--http2_port=9000",
            "--backend=grpc://127.0.0.1:50051",
            "--service=grpc.endpoints.test-deploy-242000.cloud.goog",
            "--rollout_strategy=managed",
          ]
          ports:
            - containerPort: 9000
        - name: grpc-server
          image: gcr.io/test-deploy-242000/java-grpc
          ports:
            - containerPort: 50051